import { createActivityFingerprint, planPedagogicalIntervention } from "../intervention-engine.mjs";

const language = () => document.querySelector("#locale").value;
const localized = text => ({ es:text,en:text,pt:text,fr:text,it:text,de:text });
const base={id:"mother-question",conceptId:"family-mother",learningObjectiveId:"family-1",type:"multiple-choice",skill:"vocabulary",difficulty:"foundation-1",prompt:localized("¿Cómo se dice mamá?"),options:[{id:"sy",label:"Sy"},{id:"ru",label:"Ru"},{id:"mita",label:"Mitã"}],correctOptionId:"sy"};
const audio={...base,id:"mother-audio",type:"listening",skill:"listening",prompt:localized("Escucha y elige la palabra de la imagen."),instruction:localized("Usa la imagen y el audio."),audioText:"Sy",image:"mother"};
const matching={...base,id:"mother-matching",type:"matching",prompt:localized("Relaciona integrantes de la familia."),options:[],pairs:[{id:"mother",left:"Sy",right:localized("mamá")},{id:"father",left:"Ru",right:localized("papá")}]};
const fill={...base,id:"mother-fill",type:"fill-blank",skill:"writing",prompt:localized("Completa la frase guiada."),template:localized("Mi mamá: {{blank}}"),acceptedAnswers:["Sy"],options:[]};
const pool=[base,audio,matching,fill];let current=base,attempt=0,recent=[],interventions=[];

function renderActivity(activity){current=activity;document.querySelector("#prompt").textContent=activity.prompt?.[language()]||activity.prompt?.es||activity.prompt;document.querySelector("#media").classList.toggle("hide",!activity.image);document.querySelector("#options").classList.toggle("hide",activity.id!==base.id);document.querySelector("#again").classList.toggle("hide",activity.id===base.id)}
function fail(){attempt+=1;const context={correct:false,conceptId:"family-mother",learningObjectiveId:"family-1",currentSkill:current.skill,activityType:current.type,difficulty:"foundation-1",studentAnswer:"Ru",correctAnswer:"Sy",attemptNumber:attempt,recentErrors:interventions.map(item=>({conceptId:"family-mother",errorType:item.errorType})),recentActivityFingerprints:recent,modalitiesAlreadyUsed:interventions.map(item=>item.nextActivityType),recentInterventions:interventions,uiLocale:language(),activity:current,availableActivities:pool};const plan=planPedagogicalIntervention(context);recent.push(plan.previousFingerprint,plan.nextFingerprint);interventions.push(plan);document.querySelector("#result").innerHTML=`<div class="strategy">${plan.errorType}</div><p>${plan.strategy}</p><div class="fingerprint">${plan.previousFingerprint}<br>→ ${plan.nextFingerprint}</div>`;document.querySelector("#flow").innerHTML=interventions.map((item,index)=>`<div><b>Error ${index+1}</b><br>${item.previousActivityType} → ${item.nextActivityType}<br><small>${item.strategy}</small></div>`).join("");if(plan.nextActivity)renderActivity(plan.nextActivity)}
document.querySelectorAll("[data-wrong]").forEach(button=>button.addEventListener("click",fail));document.querySelector("#again").addEventListener("click",fail);document.querySelector("#locale").addEventListener("change",()=>renderActivity(current));
window.NALVI_INTERVENTION_DEMO={fail,reset:()=>{current=base;attempt=0;recent=[];interventions=[];renderActivity(base)},audit:()=>({attempt,distinctFingerprints:new Set(interventions.map(item=>item.nextFingerprint)).size,interventions})};

